#!/bin/bash
#https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-centos-7

USER=`whoami`

#
# Get dependencies
#
cd ~

sudo su - root

sudo yum -y update

sudo yum -y install nginx wget http-server libicu-dev epel-release net-tools git vim 

sudo yum -y groupinstall 'Development Tools'

sudo yum -y install gcc-c++ make

sudo curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -

sudo yum install -y nodejs

which node

node -v

npm -v

sudo npm install -g forever

sudo systemctl start nginx

sudo systemctl enable nginx

sudo npm install -g pm2@latest -g http-server

sudo wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo

sudo yum -y install yarn


#
# Setting up web root
#
sudo mkdir -p /var/www/html

sudo chown -R www:wheel /var/www/html

cd /var/www/html

echo 'export PATH=/var/www/html:$PATH' >>~/.bashrc

source ~/.bashrc

curl -w "\n" http://169.254.169.254/metadata/v1/interfaces/private/0/ipv4/address

sudo yarn install


#
# Install node dependencies 
#
sudo yarn install

sudo su - root

sudo pm2 start node_modules/discord-token-generator/server.js --name discord-token-generator

pm2 ls

pm2 save

sudo su - $USER 


# Fix the permission issue that prevents nginx from running
sudo setenforce Permissive

sudo chcon -Rt httpd_sys_content_t /var/www/html

sudo setenforce Enforcing

sudo systemctl restart nginx


#
# Globally nstall react for UI
#
cd /var/www/html

sudo npm install -g react-composer create-react-app

create-react-app app


##
## Head back to project root
##
#cd ../..


##
## Install mongodb
##
#npm install 

## https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-centos-7
#sudo yum -y install mongodb-org

#sudo systemctl start mongod

#cd tests

#node create_mongodb.js

#npm install mongoose --save

#npm install body-parser --save


##
## Configure mongodb
##
#mongod --port 27017 --dbpath /var/lib/mongo

#sudo systemctl start mongod


#use likelycloud


